MCORE-427: запись скриншотов на ферме
tutu-ru-mobile/github-workflows pull request #48
Opened 2024-08-16 16:50 UTC by astoriawinter

https://hq.tutu.ru/browse/MCORE-427

2024-08-19 09:34 UTC, creati8e requested changes

2024-08-19 09:34 UTC, creati8e commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +      marathon_clear_package_data:
почему env variables передаются отдельно? Таких флагов может быть сколько угодно много, к тому же конкретно этот - это частный случай для рекорда снапшотов.
инпуты джобы нужно делать более общими

2024-08-19 09:34 UTC, creati8e commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +        run: cp -r ptt/ptt_app/src/androidTest/farm_resources/* ptt/ptt_app/src/androidTest/resources
Что в реюзабле делает хардкод пути к птт?

2024-08-19 09:34 UTC, creati8e commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +          adb devices | tail -n +2 | cut -sf 1 | \
можно, пожалуйста, хотя бы комментарий какую черную магию делает этот набор символов?

2024-08-19 09:34 UTC, creati8e commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +      - name: Send workflow telemetry
continue-on-error: true?

2024-08-19 09:34 UTC, creati8e commented on .github/workflows/run_ui_tests.yml
> +      branch:
в реюзабле не должно быть никаких нюансов конкретного приложения.
Реюзабл будет использоваться в солюшенах

2024-09-02 12:13 UTC, astoriawinter commented on .github/workflows/run_ui_tests.yml
> +      branch:
Солюшены используют другой скрипт, унифицировать их смысла нет, тк они слишком разные

2024-09-02 12:55 UTC, astoriawinter commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +        run: cp -r ptt/ptt_app/src/androidTest/farm_resources/* ptt/ptt_app/src/androidTest/resources
Убрала

2024-09-02 12:55 UTC, astoriawinter commented on .github/workflows/run_farm_emulator_android_ui_tests.yml
> +      marathon_clear_package_data:
Пока оставила как есть

2024-09-02 13:04 UTC, acidlynx approved these changes

2024-09-02 13:18 UTC, VadimNek approved these changes

2024-09-02 13:21 UTC, merged